name: CI Backend

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'   # cache node_modules → nhanh hơn

      - name: Install dependencies
        run: npm install

      - name: Test (optional)
        run: npm test || echo "No test script"
